main: ${PACKAGE}.${NAME}
name: ${NAME}
version: "${VERSION}"
api-version: "${API_VERSION}"
author: ${AUTHOR}
description: "${DESCRIPTION}"
commands:
  mineverify:
    description: Start or validate a MineVerify verification.
    usage: "/mineverify [code]"
    permission: mineverify.use
permissions:
  mineverify.use:
    description: Allows players to start and validate a MineVerify verification.
    default: true
