package fr.sukikui.mineverify.link;

import java.time.Instant;
import java.util.Objects;
import java.util.Optional;
import java.util.UUID;

/**
 * In-memory link request generated by MineVerify for one remote app.
 */
public final class LinkRequest {

  private final String appId;
  private final String requestId;
  private final String code;
  private final Instant expiresAt;
  private LinkRequestState state = LinkRequestState.PENDING_VALIDATION;
  private UUID minecraftUuid;
  private String minecraftName;
  private Instant validatedAt;
  private Instant expiredAt;
  private boolean codeCreatedReported;
  private boolean validationReported;
  private boolean expirationReported;

  /**
   * Creates a pending link request.
   */
  public LinkRequest(String appId, String requestId, String code, Instant expiresAt) {
    this.appId = Objects.requireNonNull(appId, "appId");
    this.requestId = Objects.requireNonNull(requestId, "requestId");
    this.code = Objects.requireNonNull(code, "code");
    this.expiresAt = Objects.requireNonNull(expiresAt, "expiresAt");
  }

  /**
   * Marks the request as validated by a connected Minecraft player.
   */
  public synchronized boolean validate(UUID uuid, String name, Instant now) {
    if (state != LinkRequestState.PENDING_VALIDATION || isExpired(now)) {
      expireIfNeeded(now);
      return false;
    }
    minecraftUuid = Objects.requireNonNull(uuid, "uuid");
    minecraftName = Objects.requireNonNull(name, "name");
    validatedAt = Objects.requireNonNull(now, "now");
    state = LinkRequestState.VALIDATED;
    return true;
  }

  /**
   * Marks the remote app validation report as delivered.
   */
  public synchronized void markValidationReported() {
    validationReported = true;
  }

  /**
   * Marks the remote app code-created report as delivered.
   */
  public synchronized void markCodeCreatedReported() {
    codeCreatedReported = true;
  }

  /**
   * Marks the remote app expiration report as delivered.
   */
  public synchronized void markExpirationReported() {
    expirationReported = true;
  }

  /**
   * Expires the request when its deadline has passed.
   */
  public synchronized boolean expireIfNeeded(Instant now) {
    if (state == LinkRequestState.PENDING_VALIDATION && isExpired(now)) {
      expiredAt = expiresAt;
      state = LinkRequestState.EXPIRED;
      return true;
    }
    return false;
  }

  /**
   * Returns whether the request is past its expiration timestamp.
   */
  public boolean isExpired(Instant now) {
    return !now.isBefore(expiresAt);
  }

  /**
   * Returns the configured app id.
   */
  public String appId() {
    return appId;
  }

  /**
   * Returns the remote app request id.
   */
  public String requestId() {
    return requestId;
  }

  /**
   * Returns the generated MineVerify code.
   */
  public String code() {
    return code;
  }

  /**
   * Returns the expiration timestamp.
   */
  public Instant expiresAt() {
    return expiresAt;
  }

  /**
   * Returns the local lifecycle state.
   */
  public synchronized LinkRequestState state() {
    return state;
  }

  /**
   * Returns the validated Minecraft UUID.
   */
  public synchronized Optional<UUID> minecraftUuid() {
    return Optional.ofNullable(minecraftUuid);
  }

  /**
   * Returns the validated Minecraft player name.
   */
  public synchronized Optional<String> minecraftName() {
    return Optional.ofNullable(minecraftName);
  }

  /**
   * Returns the validation timestamp.
   */
  public synchronized Optional<Instant> validatedAt() {
    return Optional.ofNullable(validatedAt);
  }

  /**
   * Returns the expiration timestamp once the request has expired.
   */
  public synchronized Optional<Instant> expiredAt() {
    return Optional.ofNullable(expiredAt);
  }

  /**
   * Returns true when the generated code has not yet been reported to the remote app.
   */
  public synchronized boolean needsCodeCreatedReport() {
    return state == LinkRequestState.PENDING_VALIDATION && !codeCreatedReported;
  }

  /**
   * Returns true when validation has not yet been reported to the remote app.
   */
  public synchronized boolean needsValidationReport() {
    return state == LinkRequestState.VALIDATED && !validationReported;
  }

  /**
   * Returns true when expiration has not yet been reported to the remote app.
   */
  public synchronized boolean needsExpirationReport() {
    return state == LinkRequestState.EXPIRED && !expirationReported;
  }

  /**
   * Returns true when a terminal request can be removed from memory.
   */
  public synchronized boolean isReportedTerminal() {
    return (state == LinkRequestState.VALIDATED && validationReported)
        || (state == LinkRequestState.EXPIRED && expirationReported);
  }
}
